In [ ]:
import torch
import numpy as np

In [ ]:
a = np.array([[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15]])
a

array([[ 2,  5,  7,  9],
       [ 8,  1,  3,  4],
       [11, 13, 14, 15]])

In [ ]:
a[-1:,-4:-3]

array([[11]])

In [ ]:
# Q is declare 4 dimension tensor
a = np.array( [[[[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]], [[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]], [[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]], [[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]] ], [[[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]], [[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]], [[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]], [[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]] ], [[[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]], [[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]], [[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]], [[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]] ], [[[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]], [[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]], [[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]], [[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]] ]] )
print(a.shape)
print(a[0][0][3][0])
print(a)

(4, 4, 4, 4)
11
[[[[ 2  5  7  9]
   [ 8  1  3  4]
   [11 13 14 15]
   [11 13 14 15]]

  [[ 2  5  7  9]
   [ 8  1  3  4]
   [11 13 14 15]
   [11 13 14 15]]

  [[ 2  5  7  9]
   [ 8  1  3  4]
   [11 13 14 15]
   [11 13 14 15]]

  [[ 2  5  7  9]
   [ 8  1  3  4]
   [11 13 14 15]
   [11 13 14 15]]]


 [[[ 2  5  7  9]
   [ 8  1  3  4]
   [11 13 14 15]
   [11 13 14 15]]

  [[ 2  5  7  9]
   [ 8  1  3  4]
   [11 13 14 15]
   [11 13 14 15]]

  [[ 2  5  7  9]
   [ 8  1  3  4]
   [11 13 14 15]
   [11 13 14 15]]

  [[ 2  5  7  9]
   [ 8  1  3  4]
   [11 13 14 15]
   [11 13 14 15]]]


 [[[ 2  5  7  9]
   [ 8  1  3  4]
   [11 13 14 15]
   [11 13 14 15]]

  [[ 2  5  7  9]
   [ 8  1  3  4]
   [11 13 14 15]
   [11 13 14 15]]

  [[ 2  5  7  9]
   [ 8  1  3  4]
   [11 13 14 15]
   [11 13 14 15]]

  [[ 2  5  7  9]
   [ 8  1  3  4]
   [11 13 14 15]
   [11 13 14 15]]]


 [[[ 2  5  7  9]
   [ 8  1  3  4]
   [11 13 14 15]
   [11 13 14 15]]

  [[ 2  5  7  9]
   [ 8  1  3  4]
   [11 13 14 15]
   [11 13 14 15]]

In [ ]:
#a = np.array( [[[[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]], [[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]]], [[[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]], [[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]]]] )

In [ ]:
# a = np.array( [[[[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]], [[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]]], [[[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]], [[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]]], [[[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]], [[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]]], [[[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]], [[2, 5, 7 , 9], [8, 1 , 3 , 4], [11 ,13, 14 , 15], [11 ,13, 14 , 15]]]] )
# print(a.shape)